### ISSUE TITLE
Update code to work with most recent libp2p

### ISSUE THREAD

**Issue by hubertokf** [beingmohit/libp2p-rpc#3]
Hi @beingmohit !

I really liked your project, and i'm going to use it in my master degree. Now I'm working on a uptate to make it work with most recent libp2p code.

So I'm stuck where the rpc receive a request. My nodes are not receiving anything. If you want, you can see it on my [fork](https://github.com/hubertokf/libp2p-rpc).

**Comment by hubertokf** [comment]
Sorry! I did not see that there are more recent commits. Actually npm package is outdated. So I'm closing this issue. 

Thanks!

**Comment by beingmohit** [comment]
Let me know if it still does not work, I will have a look at it.
